[package]
name = "concurrent_hash_table"
version = "0.1.0"
authors = ["kletska <kletska.epa@hotmail.com>"]
edition = "2018"


[dependencies]
crossbeam-epoch = "0.8.2"
parking_lot = "0.10"
num_cpus = "1.12.0"
rayon = {version = "1.3", optional = true}
serde = {version = "1.0.105", optional = true}